services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - smu8-ticket-network
    volumes:
      - ./frontend/:/frontend
      - frontend_node_modules:/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./backend-ticket
      dockerfile: Dockerfile.local
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend-ticket:/backend
      - backend_gradle_cache:/root/.gradle
      - backend_file_dir:/app/upload-dir
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - TZ=UTC
    depends_on:
      database:
        condition: service_healthy
    networks:
      - smu8-ticket-network
  database:
    build:
      context: ./database
      dockerfile: Dockerfile.local
    container_name: database
    ports:
      - "3306:3306"
    networks:
      - smu8-ticket-network
    volumes:
      - mysql_database:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$root']
      timeout: 20s
      retries: 10
  redis-ticket:
    build:
      context: ./redis-ticket
      dockerfile: Dockerfile.dev
    container_name: redis-ticket
    ports:
      - "6379:6379"
    networks:
      - smu8-ticket-network
volumes:
  frontend_node_modules:
  backend_gradle_cache:
  mysql_database:
  backend_file_dir:
networks:
  smu8-ticket-network:
    driver: bridge