services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - smu8-ticket-network
  backend:
    build:
      context: ./backend-ticket
      dockerfile: Dockerfile.test
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=test
    networks:
      - smu8-ticket-network
    volumes:
      - backend_file_dir:/app/upload-dir
  database:
    build:
      context: ./database
      dockerfile: Dockerfile.test
    container_name: database
    ports:
      - "3306:3306"
    networks:
      - smu8-ticket-network
    volumes:
      - mysql_database:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$root']
      timeout: 20s
      retries: 10
  redis-ticket:
    build:
      context: ./redis-ticket
      dockerfile: Dockerfile.dev
    container_name: redis-ticket
    ports:
      - "6379:6379"
    networks:
      - smu8-ticket-network
  redis-waiting:
    build:
      context: ./redis-waiting
      dockerfile: Dockerfile.test-waiting
    container_name: redis-waiting
    ports:
      - "6381:6379"
    networks:
      - smu8-ticket-network
volumes:
  mysql_database:
  backend_file_dir:
networks:
  smu8-ticket-network:
    driver: bridge