services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile.dev
    container_name: database
    ports:
      - "3306:3306"
    networks:
      - smu8-ticket-network
    volumes:
      - mysql_database:/var/lib/mysql
  redis-ticket:
    build:
      context: ./redis-ticket
      dockerfile: Dockerfile.dev
    container_name: redis-ticket
    ports:
      - "6379:6379"
    networks:
      - smu8-ticket-network
  redis-file:
    build:
      context: ./redis-file
      dockerfile: Dockerfile.dev
    container_name: redis-file
    ports:
      - "6380:6380"
    networks:
      - smu8-ticket-network
    volumes:
      - redis_file_volume:/data
volumes:
  mysql_database:
  redis_file_volume:
networks:
  smu8-ticket-network:
    driver: bridge