spring:
  config:
    activate:
      on-profile: local-dev-waiting
  data:
    redis-waiting:
      host: localhost
      port: 6381
cors:
  origins:
    - http://localhost:5173
    - http://192.168.0.6:80
    - http://192.168.0.6
  headers:
    - Content-Type
    - Authorization
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
    - HEAD
  credentials: true