spring:
  application:
    name: waiting
  profiles:
    active: local-dev-waiting
  jackson :
    time-zone: UTC
server:
  port: 8081

waiting:
  admission:
    enabled: true
    fixed-delay-millis: 1000
    count-per-cycle: 10
    active-ttl-seconds: 300
    lock-ttl-millis: 1000
