spring:
  config:
    activate:
      on-profile: load-test

  datasource:
    url: jdbc:mysql://database:3306/smu8ticket
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  data:
    redis-ticket:
      host: redis-ticket
      port: 6379
  storage:
    url: http://192.168.0.6:8080/api/images
cors:
  origins:
    - http://localhost:5173
    - http://192.168.0.6:80
    - http://192.168.0.6
  headers:
    - Content-Type
    - Authorization
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
    - HEAD
  credentials: true
logging:
  level:
    com.smu8.ticket: Debug
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
