spring:
  application:
    name: ticket
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jackson :
    time-zone: UTC

reservation:
  preempt-seat:
    ttl-seconds: 300
