spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://database:3306/smu8ticket
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis-ticket:
      host: redis-ticket
      port: 6379
  storage:
    url: http://localhost:8080/api/images

  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
cors:
  origins:
    - http://localhost:5173
  headers:
    - Content-Type
    - Authorization
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
    - HEAD
  credentials: true
logging:
  level:
    org.springframework:
      web: Debug
      security: Debug
    com.smu8.ticket: Trace
server:
  port: 8080