spring:
  config:
    activate:
      on-profile: local-test-waiting

  datasource:
    url: jdbc:mysql://database:3306/smu8ticket
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  data:
    redis-ticket:
      host: redis-ticket
      port: 6379
    redis-waiting:
      host: redis-waiting
      port: 6379
  storage:
    url: http://localhost:8080/api/images
cors:
  origins:
    - http://localhost:80
    - http://localhost
  headers:
    - Content-Type
    - Authorization
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - PATCH
    - HEAD
  credentials: true
logging:
  level:
    com.smu8.ticket: Debug
server:
  port: 8080
token:
  secret: mWy0rsOo1NgP8KGnEwgOFPZaR7auleEy+BP+1bAOB1M=
  algorithm: HmacSHA256
  access-token:
    prefix: "access-token:"
    expire: 3600
  refresh-token:
    prefix: "refresh-token:"
    expire: 7200

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

