global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: backend-ticket
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - backend-ticket:8080

  - job_name: backend-waiting
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - backend-waiting:8081

  - job_name: mysql
    static_configs:
      - targets:
          - mysql-exporter:9104

  - job_name: redis-ticket
    static_configs:
      - targets:
          - redis-ticket-exporter:9121

  - job_name: redis-waiting
    static_configs:
      - targets:
          - redis-waiting-exporter:9121
