FROM eclipse-temurin:21-jdk

WORKDIR /backend

COPY gradlew .
COPY gradle ./gradle
COPY build.gradle .
COPY settings.gradle .

RUN chmod +x ./gradlew

EXPOSE 8080

CMD ["sh", "-c", "./gradlew -t classes --no-daemon & ./gradlew bootRun --no-daemon"]