FROM eclipse-temurin:21-jre-alpine

WORKDIR /app
COPY . /app

RUN chmod +x ./gradlew

RUN ./gradlew clean
RUN ./gradlew classes
RUN ./gradlew bootJar

WORKDIR /app/build/libs
CMD ["java", "-jar", "smu8ticket-backend.jar"]